// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var cache, lastfm;
    cache = new LastFMCache();
    lastfm = new LastFM({
      apiKey: 'e3d64479d574074eac7058d08de0dda7',
      apiSecret: '063d322566d3a8bcbd48ac160aa5097a',
      cache: cache
    });
    return lastfm.track.getSimilar({
      artist: 'rihanna',
      track: 'umbrella',
      limit: 10
    }, {
      success: function(data) {
        var song, _i, _len, _ref;
        _ref = data.similartracks.track;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          song = _ref[_i];
          $('#sucks').append("<li><a>" + song.artist.name + " - " + song.name + "</a></li>");
        }
        return $('#sucks').listview("refresh");
      }
    }, {
      error: function(code, message) {}
    });
  });

}).call(this);
